site_name: RepApp - Makespace Repair-Café Hilpoltstein
site_url: https://makes-hacks-hip.github.io/RepApp/
nav:
    - RepApp:
        - Beschreibung: 'index.md'
        - Anforderungen: 'use_cases.md'
        - Abläufe: 'workflows.md'
        - Ansichten: 'views.md'
        - Daten-Modell: 'models.md'
    - 'Developer documentation':
        - Overview: 'dev/index.md'
        - Users: 'dev/users.md'
        - Stories: 'dev/stories.md'
        - 'Use cases': 'dev/use_cases.md'
        - Apps: 'dev/apps.md'
        - Objects: 'dev/objects.md'
    - 'Repair-Café & Makespace':
        - Repair-Café: https://www.repaircafe-hilpoltstein.de
        - Makespace: https://makes-hacks-hip.de
        - Makerspace@Github: https://makes-hacks-hip.github.io
theme: readthedocs
repo_url: https://github.com/makes-hacks-hip/RepApp/
edit_uri: edit/main/docs/
