site_name: RepApp - Makespace Repair-Café Hilpoltstein
site_url: https://makes-hacks-hip.github.io/RepApp/
nav:
    - 'Repair-Café & Makespace':
        - Repair-Café: https://www.repaircafe-hilpoltstein.de
        - Makespace: https://makes-hacks-hip.de
        - Makerspace@Github: https://makes-hacks-hip.github.io
theme: readthedocs
repo_url: https://github.com/makes-hacks-hip/RepApp/
edit_uri: edit/main/docs/
