# Generated by Django 4.2 on 2023-04-16 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termin',
            name='cafeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repapp.cafe'),
        ),
        migrations.AlterField(
            model_name='termin',
            name='gerätid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repapp.gerät'),
        ),
        migrations.AlterField(
            model_name='termin',
            name='reparateurid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repapp.reparateur'),
        ),
        migrations.CreateModel(
            name='Frage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frage', models.TextField()),
                ('antwort', models.TextField()),
                ('datum', models.DateField()),
                ('gerätid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repapp.gerät')),
                ('organisatorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repapp.organisator')),
                ('reparateurid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repapp.reparateur')),
            ],
        ),
    ]
