# Generated by Django 4.2 on 2023-04-24 17:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('repapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Nachricht')),
                ('answer', models.TextField(verbose_name='Antwort')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Erstellungsdatum')),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repapp.guest', verbose_name='Gast')),
            ],
            options={
                'verbose_name': 'Nachricht',
                'verbose_name_plural': 'Nachrichten',
            },
        ),
    ]
