# Generated by Django 4.2 on 2023-04-16 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repapp', '0002_alter_termin_cafeid_alter_termin_gerätid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frage',
            name='organisatorid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repapp.organisator'),
        ),
        migrations.AlterField(
            model_name='frage',
            name='reparateurid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repapp.reparateur'),
        ),
        migrations.AlterField(
            model_name='termin',
            name='gerätid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repapp.gerät'),
        ),
    ]
