# Generated by Django 4.2 on 2023-04-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repapp', '0003_guest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimelogin',
            name='secret',
            field=models.CharField(max_length=200, unique=True, verbose_name='Geheimnis'),
        ),
    ]
