# Generated by Django 4.2 on 2023-04-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repapp', '0004_appointment_device_question_remove_termin_cafeid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='event_date',
            field=models.DateField(verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Ort'),
        ),
    ]
