# Generated by Django 4.2 on 2023-04-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repapp', '0005_alter_cafe_event_date_alter_cafe_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='phone',
            field=models.CharField(default='', max_length=200, verbose_name='Telefonnummer'),
        ),
        migrations.AddField(
            model_name='device',
            name='residence',
            field=models.CharField(default='', max_length=200, verbose_name='Wohnort'),
        ),
    ]
