# Generated by Django 4.2 on 2023-05-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repapp', '0005_device_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(null=True, verbose_name='Antwort'),
        ),
    ]
