# Generated by Django 4.2 on 2023-04-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repapp', '0006_device_phone_device_residence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='phone',
            field=models.CharField(max_length=200, verbose_name='Telefonnummer'),
        ),
        migrations.AlterField(
            model_name='device',
            name='residence',
            field=models.CharField(max_length=200, verbose_name='Wohnort'),
        ),
    ]
