# Generated by Django 4.2 on 2023-04-17 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repapp', '0007_alter_device_phone_alter_device_residence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=200, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('phone', models.CharField(max_length=200, verbose_name='Telefonnummer')),
                ('residence', models.CharField(max_length=200, verbose_name='Wohnort')),
                ('mail', models.CharField(max_length=200, verbose_name='eMail')),
            ],
            options={
                'verbose_name': 'Gast',
                'verbose_name_plural': 'Gäste',
            },
        ),
        migrations.RemoveField(
            model_name='device',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='device',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='device',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='device',
            name='residence',
        ),
        migrations.AddField(
            model_name='device',
            name='guestid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repapp.guest', verbose_name='Gast'),
        ),
    ]
