# Generated by Django 4.2 on 2023-04-17 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repapp', '0008_guest_remove_device_mail_remove_device_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='cafeid',
            new_name='cafe_id',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='deviceid',
            new_name='device_id',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='reparateurid',
            new_name='reparateur_id',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='guestid',
            new_name='guest_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='deviceid',
            new_name='device_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='organisatorid',
            new_name='organisator_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='reparateurid',
            new_name='reparateur_id',
        ),
    ]
