# Generated by Django 4.2 on 2023-05-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repapp', '0008_question_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answered',
            field=models.BooleanField(default=False, verbose_name='beantwortet'),
        ),
    ]
