# Generated by Django 4.2 on 2023-06-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repapp', '0009_question_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notifications',
            field=models.BooleanField(default=True, verbose_name='Benachrichtigungen'),
        ),
    ]
