# Generated by Django 4.2 on 2023-04-20 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repapp', '0010_candidate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='cafe_id',
            new_name='cafe',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='device_id',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='reparateur_id',
            new_name='reparateur',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='cafe_id',
            new_name='cafe',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='device_id',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='guest_id',
            new_name='guest',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='device_id',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='organisator_id',
            new_name='organisator',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='reparateur_id',
            new_name='reparateur',
        ),
        migrations.AddField(
            model_name='device',
            name='cafe',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='repapp.cafe', verbose_name='Repair-Café'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Bestätigt'),
        ),
        migrations.AddField(
            model_name='device',
            name='secret',
            field=models.CharField(default='TEST12345', max_length=200, verbose_name='Bestätigungscode'),
        ),
        migrations.AddField(
            model_name='guest',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Bestätigt'),
        ),
    ]
