# Generated by Django 4.2 on 2023-06-18 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repapp', '0010_customuser_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparateur',
            name='cafe',
            field=models.ManyToManyField(to='repapp.cafe'),
        ),
        migrations.AlterField(
            model_name='device',
            name='guest',
            field=models.ForeignKey(choices=[(-1, 'abgelehnt'), (0, 'neu'), (1, 'in Orga Rückfrage'), (2, 'in Orga Rückfrage beantwortet'), (3, 'in der Warteliste')], null=True, on_delete=django.db.models.deletion.CASCADE, to='repapp.guest', verbose_name='Gast'),
        ),
    ]
