# Generated by Django 4.2 on 2023-06-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repapp', '0011_reparateur_cafe_alter_device_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparateur',
            name='cafe',
        ),
        migrations.AddField(
            model_name='cafe',
            name='reparateur',
            field=models.ManyToManyField(to='repapp.reparateur'),
        ),
    ]
