# Generated by Django 4.2 on 2023-04-21 15:21

from django.db import migrations, models
import repapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('repapp', '0011_rename_cafe_id_appointment_cafe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='secret',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='cafe',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='Ort'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='device_picture',
            field=models.FileField(null=True, upload_to=repapp.models.device_directory_path, verbose_name='Foto vom Gerät'),
        ),
        migrations.AddField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(default='', max_length=200, verbose_name='Hersteller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='type_plate_picture',
            field=models.FileField(null=True, upload_to=repapp.models.device_directory_path, verbose_name='Foto vom Typenschild'),
        ),
        migrations.AlterField(
            model_name='device',
            name='confirmed',
            field=models.BooleanField(verbose_name='Bestätigung gesendet?'),
        ),
    ]
