# Generated by Django 4.2 on 2023-06-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repapp', '0012_remove_reparateur_cafe_cafe_reparateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='reparateur',
            field=models.ManyToManyField(to='repapp.reparateur'),
        ),
    ]
