# Generated by Django 4.2 on 2023-06-18 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repapp', '0013_device_reparateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='reparateur',
            field=models.ManyToManyField(null=True, to='repapp.reparateur'),
        ),
        migrations.AlterField(
            model_name='device',
            name='guest',
            field=models.ForeignKey(choices=[(-1, 'abgelehnt'), (0, 'neu'), (1, 'in Orga Rückfrage'), (2, 'in Orga Rückfrage beantwortet'), (3, 'in der Warteliste'), (4, 'in Repa Rückfrage'), (5, 'in Repa Rückfrage beantwortet')], null=True, on_delete=django.db.models.deletion.CASCADE, to='repapp.guest', verbose_name='Gast'),
        ),
        migrations.AlterField(
            model_name='device',
            name='reparateur',
            field=models.ManyToManyField(null=True, to='repapp.reparateur'),
        ),
    ]
